---
- name: Install VDA Pre-Reqs
  win_feature:
    name: "{{ citrix_rdsh_vda_prereqs }}"
    state: present
  register: vda_prereqs 

- name: Reboot if features require
  win_reboot:
  when: vda_prereqs.reboot_required

- name: Map SMB share
  win_shell: |
    net use \\10.10.1.22 '{{ smb_share_password }}' /user:'{{ smb_share_username }}'

- name: create log folder
  win_file: 
    path: '{{ citrix_logfolder }}'
    state: directory

- name: Create install folder
  win_file: 
    path: '{{ citrix_installfolder }}'
    state: directory

- name: Copy Citrix ISO
  ansible.windows.win_copy:
    src: "{{ citrix_sources_path }}\\{{ citrix_version_name }}.iso"
    remote_src: true
    dest: C:\Install\{{ citrix_version_name }}.iso

- name: Ensure an ISO is mounted
  community.windows.win_disk_image:
    image_path: C:\Install\{{ citrix_version_name }}.iso
    state: present
  register: disk_image_out

- name: Install VDA Components
  win_package:
    path: "{{ disk_image_out.mount_paths[0] }}\\x64\\XenDesktop Setup\\XenDesktopVdaSetup.exe"
    arguments: /quiet /optimize /components vda /controllers '{{ citrix_site_DDC }}' /enable_remote_assistance /enable_hdx_ports /enable_real_time_transport /virtualmachine /noreboot /noresume /logpath 'C:\Logs' /masterimage
    state: present
    expected_return_code: [0, 3, 3010]
    creates_service: BrokerAgent
  register: vda_install

- name: Reboot after VDA
  win_reboot:
  when: vda_install.changed
